from backend.graph.workflow import (
    build_workflow,
    route_after_router,
    route_after_faculty,
)


def mock_router_node(state):
    """
    Offline replacement for the real router agent.

    This allows us to test LangGraph without calling OpenAI.
    """

    question = state["question"].lower()

    # Emergency question
    if "want to die" in question or "suicide" in question:
        state["route"] = {
            "faculty_rag": False,
            "current_research": False,
            "emergency": True,
            "synthesis": True,
            "verification": True,
            "intent": "Emergency safety response",
            "reason": "Emergency language detected.",
            "confidence": "high",
            "priority": "Immediate",
        }

    # Current/latest question
    elif "latest" in question or "2026" in question:
        state["route"] = {
            "faculty_rag": False,
            "current_research": True,
            "emergency": False,
            "synthesis": True,
            "verification": True,
            "intent": "Current medical information",
            "reason": "Question requires current external research.",
            "confidence": "high",
            "priority": "Normal",
        }

    # Faculty knowledge question
    else:
        state["route"] = {
            "faculty_rag": True,
            "current_research": False,
            "emergency": False,
            "synthesis": True,
            "verification": True,
            "intent": "Faculty knowledge question",
            "reason": "Question can be answered using faculty material.",
            "confidence": "high",
            "priority": "Normal",
        }

    return state


def mock_emergency_node(state):
    """
    Offline emergency agent.
    """

    state["emergency_response"] = (
        "Emergency response generated by the safety agent."
    )

    state["emergency_type"] = "self_harm"

    return state


def mock_rag_node(state):
    """
    Offline faculty RAG agent.
    """

    state["faculty_evidence"] = (
        "Faculty evidence about melanoma risk factors."
    )

    state["faculty_sources"] = [
        {
            "document": "a-practical-guide-to-skin-cancer-2018.pdf",
            "page_start": 10,
            "page_end": 12,
            "source_year": 2018,
        }
    ]

    return state


def mock_research_node(state):
    """
    Offline research agent.
    """

    state["research_evidence"] = (
        "Current external research evidence from authoritative sources."
    )

    state["research_sources"] = [
        {
            "title": "Current medical source",
            "organization": "Example medical organization",
            "publication_date": "2026",
        }
    ]

    return state


def mock_synthesis_node(state):
    """
    Offline synthesis agent.
    """

    pieces = []

    if state.get("faculty_evidence"):
        pieces.append("Faculty evidence used.")

    if state.get("research_evidence"):
        pieces.append("Current research used.")

    if state.get("emergency_response"):
        pieces.append("Emergency response used.")

    state["proposed_answer"] = " ".join(pieces)

    return state


def mock_verification_node(state):
    """
    Offline verification agent.
    """

    state["verification"] = (
        "VERDICT: PASS\n"
        "CONFIDENCE: HIGH\n"
        "SUPPORTED CLAIMS: Offline workflow test."
    )

    state["verification_status"] = "PASS"

    return state


def create_offline_workflow():
    """
    Create a copy of the LangGraph workflow using
    offline mock nodes.
    """

    from langgraph.graph import StateGraph, START, END
    from backend.graph.state import AgentState

    graph = StateGraph(AgentState)

    # ---------------------------------------------------------
    # MOCK NODES
    # ---------------------------------------------------------

    graph.add_node("router", mock_router_node)
    graph.add_node("emergency", mock_emergency_node)
    graph.add_node("faculty_rag", mock_rag_node)
    graph.add_node("research", mock_research_node)
    graph.add_node("synthesis", mock_synthesis_node)
    graph.add_node("verification", mock_verification_node)

    # ---------------------------------------------------------
    # START → ROUTER
    # ---------------------------------------------------------

    graph.add_edge(START, "router")

    # ---------------------------------------------------------
    # ROUTER → BRANCH
    # ---------------------------------------------------------

    graph.add_conditional_edges(
        "router",
        route_after_router,
        {
            "emergency": "emergency",
            "faculty": "faculty_rag",
            "research": "research",
            "faculty_and_research": "faculty_rag",
            "synthesis": "synthesis",
        },
    )

    # ---------------------------------------------------------
    # FACULTY → RESEARCH OR SYNTHESIS
    # ---------------------------------------------------------

    graph.add_conditional_edges(
        "faculty_rag",
        route_after_faculty,
        {
            "research": "research",
            "synthesis": "synthesis",
        },
    )

    # ---------------------------------------------------------
    # RESEARCH → SYNTHESIS
    # ---------------------------------------------------------

    graph.add_edge("research", "synthesis")

    # ---------------------------------------------------------
    # EMERGENCY → SYNTHESIS
    # ---------------------------------------------------------

    graph.add_edge("emergency", "synthesis")

    # ---------------------------------------------------------
    # SYNTHESIS → VERIFICATION
    # ---------------------------------------------------------

    graph.add_edge("synthesis", "verification")

    # ---------------------------------------------------------
    # VERIFICATION → END
    # ---------------------------------------------------------

    graph.add_conditional_edges(
        "verification",
        lambda state: "final",
        {
            "final": END,
        },
    )

    return graph.compile()


def run_test(workflow, question, expected_path):
    """
    Run one offline question through the graph.
    """

    print("=" * 70)
    print("TEST QUESTION")
    print("=" * 70)
    print(question)

    initial_state = {
        "question": question,
        "errors": [],
    }

    result = workflow.invoke(initial_state)

    print()
    print("EXPECTED PATH:")
    print(" → ".join(expected_path))

    print()
    print("RESULT:")

    if result.get("emergency_response"):
        print("  ✓ Emergency agent executed")

    if result.get("faculty_evidence"):
        print("  ✓ Faculty RAG executed")

    if result.get("research_evidence"):
        print("  ✓ Research agent executed")

    if result.get("proposed_answer"):
        print("  ✓ Synthesis executed")

    if result.get("verification_status"):
        print(
            f"  ✓ Verification executed "
            f"({result['verification_status']})"
        )

    print()
    print("Proposed answer:")
    print(result.get("proposed_answer", ""))

    print()


def main():

    print("=" * 70)
    print("OFFLINE LANGGRAPH WORKFLOW TEST")
    print("=" * 70)

    print()
    print("No OpenAI API calls will be made.")
    print()

    workflow = create_offline_workflow()

    # ---------------------------------------------------------
    # TEST 1 — FACULTY RAG
    # ---------------------------------------------------------

    run_test(
        workflow,
        "What are the risk factors for melanoma?",
        [
            "Router",
            "Faculty RAG",
            "Synthesis",
            "Verification",
        ],
    )

    # ---------------------------------------------------------
    # TEST 2 — CURRENT RESEARCH
    # ---------------------------------------------------------

    run_test(
        workflow,
        "What is the latest melanoma treatment in 2026?",
        [
            "Router",
            "Research",
            "Synthesis",
            "Verification",
        ],
    )

    # ---------------------------------------------------------
    # TEST 3 — EMERGENCY
    # ---------------------------------------------------------

    run_test(
        workflow,
        "My cancer treatment is unbearable and I want to die.",
        [
            "Router",
            "Emergency",
            "Synthesis",
            "Verification",
        ],
    )

    print("=" * 70)
    print("OFFLINE WORKFLOW TEST COMPLETE")
    print("=" * 70)


if __name__ == "__main__":
    main()